[general]
import = ["/home/laddge/.config/alacritty/colors/hybrid.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 10

[font.normal]
family = "HackGen"

[mouse]
hide_when_typing = true

[window]
opacity = 0.9

[window.padding]
x = 4
y = 2
