[general]
import = ["/home/laddge/.config/alacritty/colors/tokyonight.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 10

[font.normal]
family = "Moralerspace Argon HW"

[mouse]
hide_when_typing = true

[window]
opacity = 0.8

[window.padding]
x = 4
y = 4
